name: example
description: A Flutter widget for creating stylized headings using HTML-like tags.
publish_to:

version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  heading_text_flutter:
    path: ../



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
